misyte/app/urls.py
from django.urls import path, include
from .views import accesorios, agregarAcc, eliminar_Accesorios, home, listar_Accesorios, modificar_Accesorios, nuestrosMininos, quienesSomos, formulario, productos, agregar_producto, listar_productos, \
modificar_producto, eliminar_producto, registro, product_list, product_detail, APIView, marca_list, accesorio_list, accesorio_detail, \
MarcaViewSet, ProductoViewSet, AccesorioViewSet, pokedex
from rest_framework import routers
from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns


#localhost:8000/api/producto/
urlpatterns = [
    path('', home, name="home"),
    path('quienesSomos/', quienesSomos, name="quienesSomos"),
    path('nuestrosMininos/', nuestrosMininos, name="nuestrosMininos"),
    path('formulario/', formulario, name="formulario"),
    path('productos/', productos, name="productos"),
    path('agregar-productos/', agregar_producto, name="agregar_producto"),
    path('listar-productos/', listar_productos, name="listar_productos"),
    path('modificar-producto/<id>/', modificar_producto, name="modificar_producto"),
    path('eliminar-producto/<id>/', eliminar_producto, name="eliminar_producto"),
    path('registro/', registro, name="registro"),
    path('pokedex/', pokedex, name="pokedex"),
    path('Accesorios/', accesorios, name="Accesorios"),
    path('agregarAcc/', agregarAcc, name="agregar_accesorios"),
    path('listarAcc/', listar_Accesorios, name="listar_accesorios"),
    path('eliminarAcc/<id>/', eliminar_Accesorios, name="eliminar_accesorios"),
    path('modificarAcc/<id>/', modificar_Accesorios, name="modificar_accesorios"),
    path('marcaApi/', marca_list.as_view()),
    path('productoApi/', product_list.as_view()),
    path('productoApi/<int:pk>/', product_detail.as_view()),
    path('accesorioApi/', accesorio_list.as_view()),
    path('accesorioApi/<int:pk>/', accesorio_detail.as_view()),
    ]

misyte/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misyte/app/models.py
from distutils.command.upload import upload
from django.db import models

class Marca(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    peso = models.FloatField(max_length=5)
    descripcion = models.TextField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    fecha_fabricacion = models.DateField()
    imagen = models.ImageField(upload_to="productos", null=True)

    def __str__(self):
        return self.nombre

opciones_consultas = [
    [0, "Adopcion"],
    [1, "Consulta"],
    [2, "Reclamo"],
    [3, "Sugerencia"],
    [4, "Felicitaciones"],
]

class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField()
    avisos = models.BooleanField()

    def __str__(self):
        return self.nombre
    
class Accesorios(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to="accesorios", null=True)

    def __str__(self):
        return self.nombre

misyte/app/templates/app/Accesorios.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/estilos_form.css' %}">
<link rel="stylesheet" href="{% static 'app/css/estiloSomos.css' %}">
<link rel="stylesheet" href="{% static 'app/css/slider.css' %}">
{% endblock %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

{% endblock %}

{% block contenido %}

<div id="contenido">

    <div class="cabeza">
  
        <ul class="slider">
          <li id="slide1">
            <img src="{% static 'app/img/banner/Gatiño.jpeg' %}"/>
          </li>
          <li id="slide2">
            <img src="{% static 'app/img/banner/Gatiño2.jpeg' %}"/>
          </li>
          <li id="slide3">
            <img src="{% static 'app/img/banner/Gatiño3.jpeg' %}"/>
          </li>
        </ul>
        <ul class="Mmenu">
          <li>
            <a href="#slide1">1</a>
          </li>
          <li>
            <a href="#slide2">2</a>
          </li>
           <li>
            <a href="#slide3">3</a>
          </li>
        </ul> 
      </div>
    {% load humanize %}
    <br>
    <h2>Accesorios</h2>
    <div class="productos">
        {% for p in accesorios %}
        <div class="producto">

            <div class="card">
                <div class="card-body">
                    </class>
                    {% if p.imagen %}
                    <img src="{{ p.imagen.url }}" alt="imagen producto">
                    {% endif %}
                    <div class="detalle">
                        <h2 class="NombreProducto">{{ p.nombre | title }}</h2>
                        <h3>${{ p.precio | intcomma }}</h3>
                        <h6>Descripcion: {{ p.descripcion | capfirst }}</h6>
                    </div>
                </div>

            </div>

        </div>
        {% endfor %}
    </div>


</div>

{% endblock %}

misyte/app/templates/app/base.html
<!DOCTYPE html>
<html class="Cuerpo" lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    {% block css %}
    {% endblock %}

    <link rel="shortcut icon" href="{% static 'app/img/LogoCats.png' %}" type="image/x-icon">
    <title>Cat's are Cute</title>
</head>
<!-- contenedor logo y barra de direcciones-->

<body>
    <header>
        <nav class="navbar navbar-light bg-light navbar-expand-lg ">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'app/img/LogoCats.png' %}" width="40" height="40" class="d-inline-block align-top"
                    alt=""> Adopta un minino
            </a>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'home' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'quienesSomos' %}">Quienes Somos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'nuestrosMininos' %}">Nuestros Mininos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'formulario' %}">Adopcion</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'productos' %}">Productos</a>
                    </li>
                    {% if perms.app.add_producto  %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'agregar_producto' %}">Agregar Productos</a>
                    </li>
                    {% endif %}
                    {% if perms.app.view_producto  %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'listar_productos' %}">Listar Productos</a>
                    </li>
                    {% endif %}
                    {% if perms.app.add_accesorio  %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'agregar_accesorios' %}">Agregar Accesorio</a>
                    </li>
                    {% endif %}
                    {% if perms.app.view_accesorio  %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'listar_accesorios' %}">Listar Accesorios</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Accesorios' %}">Accesorios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pokedex' %}">Pokedex</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class="nav-link" href="{% url 'logout' %}">Cerrar sesión</a>
                    </li>
                    <li>
                        <a class="nav-link" href="#">{{ user.username }}</a>
                    </li>
                    {% else %}
                    <li>
                        <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'registro' %}">Registrarse</a>
                    </li>
                    {% endif %}

                </ul>
            </div>
        </nav>
    </header>
    <div id="contenido">


        {% block contenido%}
        {% endblock%}

    </div>
    <!-- Contenedor Final "PIES"-->
    <div class="footer">
        <span>Todos los derechos reservados</span>
    </div>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
        {% for m in messages %}
            <script>
                Swal.fire({
                "title": "Felicitaciones",
                "text": "{{m}}",
                "icon": "success"
                })
            </script>
        {% endfor %}
    {% endif %}

    {% block js %}
    {% endblock %}
</body>

</html>

misyte/app/templates/app/formulario.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/estilos_form.css' %}">
<link rel="stylesheet" href="{% static 'app/css/estiloSomos.css' %}">
{% endblock %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.2/dist/jquery.validate.min.js"></script>
<script src="js/traducciones.js"></script>

{% endblock %}

{% block contenido %}
{% load crispy_forms_tags %}
<!-- Formulario -->
<div id="contenido">
    <br>
    <br>
    <div class="row">
        <div class="col-12 col-md-6 offset-md3">
            <div class="card">
                <div class="card-body">
                    <h2 class="titulo">Contactanos!</h2>
                    <hr>
                    <form action="" class="" method="post">

                        {% csrf_token %}
                        {{ form | crispy }}
                        <hr>
                        <br>
                        <div class="d-flex justify-content-end">
                            <button type="submit" id="btnEnviar" class="btn btn-primary">Enviar</button>
                            &nbsp;
                            <input type="reset" value="Cancelar" class="btn btn-secondary">
                        </div>



                    </form>
                    {{mensaje}}

                </div>
            </div>
        </div>
    </div>
    <table id="tablacontactos">

    </table>


</div>



{% endblock %}

misyte/app/templates/app/home.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'app/css/estilo.css' %}">
{% endblock %}

{% block js %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
{% endblock %}

{% block contenido %}

<!-- Video Inicial -->
<div class="principal">
    <object data="https://www.youtube.com/embed/u0XHVssfsYM" width="560" height="315" type="text/html">
    </object>
</div>
<!-- Contenedor inferior con datos de adopcion y financiamiento-->
<div class="contenedor-inferior container">
    <div class="row">
        <br>
        <div class="col-6 col-md-6 lateral_1">
            <h1>Adopción</h1>
            <h5>Condiciones</h5>
            <p>- Nos preocupamos de que nuestros gatos tengan seguridad, de esta forma se necesita un buen espacio.
            </p>
            <p> > Idealmente que sean indoor </p>
            <p> > Tener zonas de juegos</p>
            <p> > Amarlos, obvio es lo fundamental</p>
            <img src="{% static 'app/img/gatos5.jpg' %}" alt="gato_en_adopcion" class="col-8 col-md-8" />
        </div>
        <br>
        <div class="col-6 col-md-6 lateral_2">
            <img src="{% static 'app/img/GatoDinero.jpg' %}" alt="financiamiento" />
            <h1>RECAUDACIÓN DE FONDOS</h1>
            <h5> FINANCIAMIENTO</h5>
            <p> A base de campañas solidarias y eventos de mascotas es como financiamos nuestro mantenimiento a los
                gatos que tenemos acogidos por un tiempo.</p>
        </div>
        <br>

    </div>
</div>
<!-- Contenedor de contacto bajada de foto y redes sociales-->
<section class="contenido">
    <div class="fono">
        <h5><a>+56 9 56937133</a></h5>
    </div>
    <div class="Adopcion">
        <h5><a> Adopción de Gatos </a></h5>
    </div>
    <div class="redes">
        <ul>
            <li>
                <img src="{% static 'app/img/icons/facebook-f-brands.svg' %}" alt="facebook" />
            </li>
            <li>
                <img src="{% static 'app/img/icons/google-plus-g-brands.svg' %}" alt="google+" />
            </li>
            <li>
                <img src="{% static 'app/img/icons/instagram-brands.svg' %}" alt="instagram" />
            </li>
            <li>
                <img src="{% static 'app/img/icons/envelope-solid.svg' %}" alt="mail" />
            </li>
        </ul>
    </div>
</section>


{% endblock %}

misyte/app/templates/app/nuestrosMininos.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/galeria.css' %}">
{% endblock %}
{% block js %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script src="{% static 'app/js/main.js' %}"></script>
{% endblock %}

{% block contenido %}

<!-- Galeria completa de todas las imagenes -->

<body>
    <div class="container">
        <div class="row">
            <div class="col s12">
                <hr>
                <h1 class="center-aling titulo">¿Que Gato se Interesaria adoptar?</h1>
                <hr>
                <div class="carousel center-aling">
                    <div class="carousel-item">
                        <h2 class="subtitulo">Oliver</h2>
                        <div class="linea-division"></div>
                        <p class="sabor">Curioso</p>
                        <img src="{% static 'app/img/gatocamara.jpg' %}" alt="">
                    </div>
                    <div class="carousel-item">
                        <h2 class="subtitulo">Mario</h2>
                        <div class="linea-division"></div>
                        <p class="sabor">Flojo</p>
                        <img src="{% static 'app/img/gatodepana.jpg' %}" alt="">

                    </div>
                    <div class="carousel-item">
                        <h2 class="subtitulo">Tobias</h2>
                        <div class="linea-division"></div>
                        <p class="sabor">Agresivo</p>
                        <img src="{% static 'app/img/gatoleon.jpg' %}" alt="">

                    </div>

                    <div class="carousel-item">
                        <h2 class="subtitulo">Copito</h2>
                        <div class="linea-division"></div>
                        <p class="sabor">Cariñoso</p>
                        <img src="{% static 'app/img/gatonieve.jpg' %}" alt="">

                    </div>

                    <div class="carousel-item">
                        <h2 class="subtitulo">Calcetin</h2>
                        <div class="linea-division"></div>
                        <p class="sabor">Travieso</p>
                        <img src="{% static 'app/img/gatoreja.jpg' %}" alt="">

                    </div>
                </div>
                <hr>
            </div>

        </div>

    </div>




</body>

{% endblock %}

misyte/app/templates/app/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

misyte/app/templates/app/pokedex.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
    <link href="{% static 'app/css/styles.css' %}" rel="stylesheet" />
{% endblock %}
{% block js %}
    <script src="{% static 'app/JS/scriptpoke.js' %}" type="text/javascript" defer></script>
{% endblock %}

{% block contenido %}
<body>
    <form action="" onsubmit="searchPokemon(event)">
        <input type="text" name="pokemon" autocomplete="off">
    </form>
    <div data-poke-card class="poke-card">
        <div data-poke-name>Pokedex</div>
        <div data-poke-img-container class="img-container">
            <img data-poke-img class="poke-img" src="{% static 'app/img/poke-shadow.png' %}"/>
        </div>
        <div data-poke-id></div>
        <div data-poke-types class="poke-types"></div>
        <div data-poke-stats class="poke-stats"></div>
    </div>
</body>
{% endblock %}

misyte/app/templates/app/productos.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/estilos_form.css' %}">
<link rel="stylesheet" href="{% static 'app/css/estiloSomos.css' %}">
<link rel="stylesheet" href="{% static 'app/css/slider.css' %}">
{% endblock %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

{% endblock %}

{% block contenido %}

<div id="contenido">

    <div class="cabeza">
  
        <ul class="slider">
          <li id="slide1">
            <img src="{% static 'app/img/banner/Banner-Alimento-Gatos.png' %}"/>
          </li>
          <li id="slide2">
            <img src="{% static 'app/img/banner/baner2gatos.png' %}"/>
          </li>
          <li id="slide3">
            <img src="{% static 'app/img/banner/banner3gatos.png' %}"/>
          </li>
        </ul>
        <ul class="Mmenu">
          <li>
            <a href="#slide1">1</a>
          </li>
          <li>
            <a href="#slide2">2</a>
          </li>
           <li>
            <a href="#slide3">3</a>
          </li>
        </ul> 
      </div>
    {% load humanize %}
    <br>
    <h2>Productos</h2>
    <div class="productos">
        {% for p in productos %}
        <div class="producto">
            <div class="card">
                <div class="card-body">
                    </class>
                    {% if p.imagen %}
                    <img src="{{ p.imagen.url }}" alt="imagen producto">
                    {% endif %}
                    <div class="detalle">
                        <h5>{{ p.marca | capfirst }}</h5>
                        <h2 class="NombreProducto">{{ p.nombre | title }}</h2>
                        <h5>{{ p.peso }} Kg</h5>
                        <h3>${{ p.precio | intcomma }}</h3>
                        <h6>{{ p.descripcion | capfirst }}</h6>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>


</div>

{% endblock %}

misyte/app/templates/app/quienesSomos.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'app/css/estiloSomos.css' %}">
{% endblock %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

{% endblock %}

{% block contenido %}

    <!-- Video cabezal -->
    <div class="principal">
        <object data="https://www.youtube.com/embed/u0XHVssfsYM" width="560" height="315" type="text/html">
        </object>
    </div>
    <!-- Contenedor inferior con Somos, Mision, Redes y Veterinaria-->
    <div class="contenedor-inferior container">
        <div class="row">
            <hr>
            <div class="Somos">
                <h1>Adopta un minino</h1>
                <p> Somos una organizacion sin fines de lucro para ayudar a gatos que necesitan un hogar y nuestra
                    ayuda,
                    nos preocupamos de que tengan seguridad, alimentación, una buena salud y un lugar agradable donde
                    habitar.</p>
                <img src="{% static 'app/img/GatoAdop.webp' %}" alt="somoss" class="adop" />
            </div>
            <hr>
            <div class="Mision">
                <h1>Nuestra Misión</h1>
                <p> Llevar a cada gato a un hogar seguro, de buen entorno, mientras no tengan dicho hogar,
                    poder darles un buen lugar en el cual vivir seguros.</p>
                <img src="{% static 'app/img/Brunito.jpeg' %}" alt="bruno" />
            </div>
            <hr>
            <div class="Redes">
                <h1>Nuestras redes</h1>
                <p> A base de campañas solidarias y eventos de mascotas es como financiamos nuestro mantenimiento a los
                    gatos que tenemos acogidos por un tiempo.</p>
                <img src="{% static 'app/img/redesSociales.jpg' %}" alt="red" />
            </div>
            <hr>
            <div class="Veterinaria">
                <h1>Contamos con nuestra propia veterinaria</h1>
                <p> Constanza es quien se encarga de que los gatos acogidos esten en un buen estado de salud,
                    con sus vacunas y desparasitaciones al día, y así, sus nuevos tutores los adoptarán sanos.</p>
                <img src="{% static 'app/img/ConiIvanVet.jpeg' %}" alt="vet" />
            </div>
            <hr>
        </div>
    </div>

    {% endblock %}